---
# handlers file for ansible-role-cratedb

- name: restart crate
  service:
    name: crate
    state: restarted

- name: reload crate
  service:
    name: crate
    state: reloaded

- name: stop crate
  service:
    name: crate
    state: stopped
