---
# handlers file for ansible-role-cratedb

- name: restart cratedb
  service:
    name: cratedb
    state: restarted

- name: reload cratedb
  service:
    name: cratedb
    state: reloaded

- name: stop cratedb
  service:
    name: cratedb
    state: stopped
